name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e . pytest

      - name: Run unit + integration tests
        run: pytest -v --maxfail=1 --disable-warnings

  build:
    runs-on: ubuntu-latest
    needs: test   # Only run if tests succeed
    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/smart-inventory:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/smart-inventory:latest