name: Run Tests

on:
  push:
    branches: [ "**" ]   # run on all branches
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run unit + integration tests
        run: PYTHONPATH=. pytest -v --maxfail=1 --disable-warnings

      # Optional: separate step for Streamlit smoke test
      - name: Run Streamlit UI smoke test
        run: PYTHONPATH=. pytest tests/integration/test_ui.py -v --maxfail=1 --disable-warnings